#!/bin/zsh

cd ..

mv /usr/bkup/trism.zip /usr/bkup/trism.zip.bk

zip /usr/bkup/trism.zip data/glopts data/players data/bricks data/probs \
	src/1-* src/Imake.tmpl src/Makefile src/mk* src/tbrowse
for DIR in src/*(/)
{
	zip /usr/bkup/trism.zip $DIR/(*.(C|c|H|h)|1-*)
}
