#!/bin/zsh

# mkdistr - makes a source distribution

[[ $# != 1 ]] && { echo Usage: mkdistr outputdir; exit 1; }

DEST=$1/xtrism

mkdir -p $DEST

echo Copying sources...
mkdir -p $DEST/src
for SUB in *(/)
{ echo '   ' Copying $SUB
  mkdir -p $DEST/src/$SUB
  cp $SUB/*.(C|H|c|h) $DEST/src/$SUB
}
cp Imake.tmpl Makefile mkclean mkimake $DEST/src

echo Copying data...
mkdir -p $DEST/data
cd ../data
cp glopts players bricks probs $DEST/data

echo Done
