#!/bin/sh

SUBDIRS="basics  bytemap  env  game  globals  mainmenu  options  poll    sessions bricks  esd      gfx   main  pics     popups  sound"

cd `dirname $0`
cd ../src

echo "# Automatically generated by updatesources.sh" > xtrism.pri
echo "" >> xtrism.pri

for DIR in $SUBDIRS; do

    echo "HEADERS += \\" >> xtrism.pri
    find $DIR -maxdepth 1 -name \*.H -exec echo "    " '{}' " \\" ';' >> xtrism.pri
    echo "" >> xtrism.pri

    echo "SOURCES += \\" >> xtrism.pri
    find $DIR -maxdepth 1 -name \*.C -exec echo "    " '{}' " \\" ';' >> xtrism.pri
    echo "" >> xtrism.pri
done
