#!/bin/sh

SUBDIRS="basics game mainmenu options bricks gfx main sound"

cd `dirname $0`
cd ..
pwd

echo "# Automatically generated by updatesources.sh" > src/CMakeLists.txt
echo "" >> src/CMakeLists.txt

for DIR in $SUBDIRS; do
    echo "target_include_directories(xtrism PUBLIC src/$DIR)" >> src/CMakeLists.txt

    find src/$DIR -name \*.h -exec echo "target_sources(xtrism PRIVATE" '{}' ")" ';' | sort -df >> src/CMakeLists.txt
    find src/$DIR -name \*.cpp -exec echo "target_sources(xtrism PRIVATE" '{}' ")" ';' | sort -df >> src/CMakeLists.txt
    find src/$DIR -name \*.qrc -exec echo "target_sources(xtrism PRIVATE" '{}' ")" ';' | sort -df >> src/CMakeLists.txt
done
